# Generates content/unit-NN-cold.json for units 2-10 (Workstream C1).
# Reuses each original unit's vocab + cutscene shell; the crime, dialogue,
# reading and lineup are authored per unit below. Run: python scripts/generate-cold-cases.py
import json, io, os

BASE = os.path.join(os.path.dirname(__file__), "..", "content")

def load(n):
    with io.open(os.path.join(BASE, f"unit-{n:02d}.json"), encoding="utf-8") as f:
        return json.load(f)

# d = dialogue helper
def dlg(npc, avatar, clue, n1, opts1, n2, opts2, end_line, end_msg):
    return {
        "type": "dialogueChoice", "clueReward": clue, "npcName": npc, "npcAvatar": avatar,
        "startNodeId": "start",
        "nodes": [
            {"id": "start", "npcLine": n1, "options": opts1},
            {"id": "info", "npcLine": n2, "options": opts2},
            {"id": "detail", "npcLine": end_line, "isEnd": True, "endMessage": end_msg},
        ],
    }

def opt(text, ok, nxt=None, fb=None):
    o = {"text": text, "isCorrect": ok}
    if ok and nxt: o["nextNodeId"] = nxt
    if not ok and fb: o["feedback"] = fb
    return o

def mc(qid, text, options, ci, es, en):
    return {"id": qid, "text": text, "type": "multiple_choice", "options": options,
            "correctIndex": ci, "explanationEs": es, "explanationEn": en}

def sa(qid, text, answers, es, en):
    return {"id": qid, "text": text, "type": "short_answer", "acceptableAnswers": answers,
            "explanationEs": es, "explanationEn": en}

def sus(sid, name, real, age, desc, seed):
    return {"id": sid, "name": name, "realName": real, "age": age, "description": desc, "imageSeed": seed}

COLD = {
2: dict(
  caseTitle="El Robo del Trofeo", criminalName="La Directora Falsa",
  caseDescription="Un mes después del hackeo, el trofeo de campeones de la Escuela Central de San Juan desapareció durante la semana de exámenes. Una 'directora visitante' firmó el registro… pero ninguna escuela la envió. Las pistas son más difíciles y los testigos solo hablan español.",
  bonusClue="La sospechosa llevaba gafas de sol DENTRO de la escuela y firmó el registro con la mano izquierda.",
  briefing=["Agente, bienvenido de nuevo a San Juan. La escuela nos necesita otra vez.",
            "El trofeo de campeones desapareció de la vitrina de la biblioteca durante los exámenes.",
            "Una mujer entró como 'directora visitante', pero ninguna escuela la envió. Es una profesional.",
            "Los testigos solo hablan español y tienes menos tiempo. Este caso es frío, difícil y vale doble. ¡A trabajar!"],
  dialogue=dlg("Sra. Ortiz, la bibliotecaria", "📚",
    "La sospechosa es alta, con chaqueta azul, y preguntó dónde está la vitrina de los trofeos.",
    "¡Buenos días! ¿Tú eres el agente de la agencia? Yo soy la bibliotecaria de la escuela.",
    [opt("Buenos días, señora Ortiz. Soy detective. ¿Qué vio usted ayer?", True, "info"),
     opt("Hola. ¿Dónde están los libros de historia?", False, fb="Los libros no importan ahora — preséntate y pregunta sobre el robo."),
     opt("Adiós, gracias.", False, fb="¡Espera! La bibliotecaria vio a la sospechosa. Saluda y pregunta.")],
    "Vi a una mujer alta con una chaqueta azul. Es seria y muy organizada. Preguntó dónde está la vitrina de los trofeos. ¡Una directora real ya sabe eso!",
    [opt("¿Cómo es ella físicamente? ¿Algo más?", True, "detail"),
     opt("¿Qué clases enseña usted?", False, fb="Ella no es profesora — es bibliotecaria. Pregunta más sobre la sospechosa."),
     opt("¿El trofeo es grande?", False, fb="Ya sabes cómo es el trofeo. Pregunta por la DESCRIPCIÓN de la mujer.")],
    "Es alta y morena, de unos treinta y cinco años. Lleva gafas de sol dentro de la escuela — ¡qué raro! Y firmó el registro con la mano izquierda.",
    "La Sra. Ortiz vuelve a su escritorio. Tienes una descripción completa."),
  reading=dict(
    clue="La 'directora' entró a las 10:15, no fue a la oficina, y salió a las 10:40 con una bolsa deportiva grande.",
    passage="REGISTRO DE VISITANTES — ESCUELA CENTRAL DE SAN JUAN\nFecha: jueves, 12 de mayo\n\n09:50 — Los estudiantes entran a los exámenes. Los pasillos están vacíos.\n10:15 — Una mujer firma el registro como 'Directora visitante — Escuela del Este'. Letra con la mano izquierda. Lleva chaqueta azul y una bolsa deportiva vacía.\n10:20 — La visitante NO va a la oficina de la directora. Va directamente a la biblioteca.\n10:35 — La alarma de la vitrina de trofeos suena por 30 segundos y para.\n10:40 — La visitante sale por la puerta principal. La bolsa deportiva ahora se ve llena y pesada.\n11:05 — El conserje descubre la vitrina abierta y el trofeo no está.\nNota: La Escuela del Este confirma: no tienen directora visitante hoy.",
    glossary=[{"word":"registro","translation":"log / sign-in sheet"},{"word":"pasillos","translation":"hallways"},
              {"word":"letra","translation":"handwriting"},{"word":"bolsa deportiva","translation":"gym bag"},
              {"word":"conserje","translation":"janitor"},{"word":"vitrina","translation":"display case"}],
    questions=[
      mc("cr1","¿A qué hora firmó el registro la 'directora visitante'?",["09:50","10:15","10:35","11:05"],1,
         "El registro dice: «10:15 — Una mujer firma el registro».","The log shows she signed in at 10:15."),
      mc("cr2","¿Adónde fue la visitante primero?",["A la oficina","A la cafetería","A la biblioteca","Al gimnasio"],2,
         "El registro dice que NO fue a la oficina — fue directamente a la biblioteca.","She skipped the office and went straight to the library."),
      mc("cr3","¿Cómo se veía la bolsa deportiva cuando salió?",["Vacía","Llena y pesada","Pequeña","Rota"],1,
         "Al entrar la bolsa estaba vacía; al salir «se ve llena y pesada».","Empty going in, full and heavy going out."),
      sa("cr4","¿Con qué mano firmó el registro? (Escribe en español.)",["la mano izquierda","izquierda","con la izquierda"],
         "El registro dice: «Letra con la mano izquierda».","The log notes left-handed handwriting."),
    ]),
  lineup=dict(
    hint="Busca a una mujer alta y morena de unos 35 años, con chaqueta azul, gafas de sol y que escribe con la mano izquierda.",
    correct="la-directora-falsa",
    suspects=[
      sus("la-directora-falsa","La Directora Falsa","Carmen Delgado Ruiz",35,
          "Es una mujer alta y morena de treinta y cinco años. Es seria y muy organizada. Lleva una chaqueta azul y gafas de sol. Escribe con la mano izquierda.",22),
      sus("la-profesora","La Profesora","Ana Beltrán Soto",35,
          "Es una mujer alta y morena de treinta y cinco años. Es simpática y habla mucho. Lleva una chaqueta azul, pero escribe con la mano derecha y no usa gafas.",25),
      sus("el-entrenador","El Entrenador","Luis Vega Marín",42,
          "Es un hombre alto y fuerte de cuarenta y dos años. Lleva una bolsa deportiva todos los días porque es el entrenador de baloncesto de la escuela.",13),
      sus("la-secretaria","La Secretaria","Rosa Jiménez Cruz",28,
          "Es una mujer baja y rubia de veintiocho años. Es tímida y trabajadora. Escribe con la mano izquierda, pero estaba en la oficina toda la mañana.",30),
      sus("el-inspector","El Inspector","Pedro Casals Rivera",50,
          "Es un hombre delgado de cincuenta años con gafas de sol. Visita escuelas para el gobierno, pero ayer visitó otra escuela en Ponce.",8),
    ]),
),
3: dict(
  caseTitle="El Boceto Perdido", criminalName="El Turista Eterno",
  caseDescription="Meses después de capturar a La Sombra, un boceto original de Goya desapareció de una exposición temporal en el Parque del Retiro. El sospechoso escapó en metro. La red de El Tejedor sigue activa en Madrid — y este caso frío vale doble.",
  bonusClue="El sospechoso siempre lleva un mapa turístico viejo… con la estación de Atocha marcada en rojo.",
  briefing=["Agente, Madrid otra vez. La red de El Tejedor no descansa.",
            "Un boceto original de Goya desapareció de la exposición del Parque del Retiro.",
            "El sospechoso escapó en metro. Conoce la ciudad perfectamente, pero finge ser turista.",
            "Caso frío: menos tiempo, testigos solo en español, puntos dobles. ¡Al metro, agente!"],
  dialogue=dlg("Marta, la vendedora de boletos", "🎫",
    "El sospechoso compró un boleto a Atocha y preguntó cómo llegar al Retiro… aunque venía DEL Retiro.",
    "¡Hola! ¿Un boleto de metro? Ah no, ¿tú eres el detective? ¡Qué emoción!",
    [opt("Buenas tardes, Marta. Sí, soy detective. ¿Vio a un hombre con un tubo de cartel ayer?", True, "info"),
     opt("Quiero ir al museo del Prado, por favor.", False, fb="No estás de turismo — preséntate y pregunta por el sospechoso."),
     opt("¿Cuánto cuesta un boleto?", False, fb="El precio no importa. Pregunta sobre el hombre del tubo de cartel.")],
    "¡Sí! Un hombre con un tubo de carteles. Compró un boleto a Atocha. Me preguntó cómo llegar al Retiro… ¡pero él venía del Retiro! Muy raro.",
    [opt("¿Cómo es él? ¿Adónde va normalmente?", True, "detail"),
     opt("¿A qué hora cierra el metro?", False, fb="Concéntrate en el sospechoso, no en el horario del metro."),
     opt("¿El Retiro está lejos?", False, fb="Tú ya tienes un mapa. Pregunta por la DESCRIPCIÓN del hombre.")],
    "Es bajo, con sombrero de turista y una cámara vieja que nunca usa. Siempre lleva un mapa turístico viejo con la estación de Atocha marcada en rojo. Lo veo aquí cada semana.",
    "Marta te da el horario del tren a Atocha. La trampa está lista."),
  reading=dict(
    clue="El sospechoso salió de la exposición a las 17:20 con un tubo de carteles y tomó la línea 2 hacia Atocha.",
    passage="INFORME DE SEGURIDAD — EXPOSICIÓN 'GOYA EN EL RETIRO'\nFecha: domingo, 8 de junio\n\n16:45 — Un visitante con sombrero de turista entra a la carpa de la exposición. Lleva un tubo de carteles vacío, como los estudiantes de arte.\n17:00 — El visitante pregunta al vigilante dónde está el boceto original de Goya. Va directamente a esa sala.\n17:15 — Las luces de la sala fallan por dos minutos. Nadie ve nada.\n17:20 — El visitante sale caminando rápido hacia la estación de metro. El tubo de carteles ahora está cerrado con cinta.\n17:25 — Toma la línea 2 del metro en dirección a Atocha.\n17:30 — El vigilante descubre el marco vacío. El boceto no está.\nNota: El mismo hombre visitó la exposición tres veces esta semana.",
    glossary=[{"word":"boceto","translation":"sketch"},{"word":"carpa","translation":"tent / pavilion"},
              {"word":"tubo de carteles","translation":"poster tube"},{"word":"cinta","translation":"tape"},
              {"word":"marco","translation":"frame"},{"word":"vigilante","translation":"guard"}],
    questions=[
      mc("cr1","¿Qué llevaba el visitante al entrar?",["Una mochila","Un tubo de carteles vacío","Una maleta","Un estuche de música"],1,
         "El informe dice que llevaba «un tubo de carteles vacío», como los estudiantes de arte.","He carried an empty poster tube — perfect for hiding a sketch."),
      mc("cr2","¿Qué pasó a las 17:15?",["Cerró la exposición","Las luces fallaron dos minutos","Llegó la policía","Empezó a llover"],1,
         "A las 17:15 «las luces de la sala fallan por dos minutos» — el momento del robo.","The lights failed for two minutes — the moment of the theft."),
      mc("cr3","¿Qué línea de metro tomó y en qué dirección?",["Línea 1 a Sol","Línea 2 a Atocha","Línea 5 a Callao","Línea 3 a Moncloa"],1,
         "El informe dice: «Toma la línea 2 del metro en dirección a Atocha».","Line 2 toward Atocha — the same station marked on his map."),
      sa("cr4","¿Cuántas veces visitó el hombre la exposición esta semana?",["tres","tres veces","3"],
         "La nota dice: «El mismo hombre visitó la exposición tres veces esta semana».","He cased the exhibition three times."),
    ]),
  lineup=dict(
    hint="Busca a un hombre bajo con sombrero de turista, una cámara que nunca usa, un tubo de carteles y un mapa con Atocha marcada en rojo.",
    correct="el-turista-eterno",
    suspects=[
      sus("el-turista-eterno","El Turista Eterno","Julián Herrero Blanco",38,
          "Es un hombre bajo de treinta y ocho años con sombrero de turista. Lleva una cámara vieja que nunca usa y un tubo de carteles. Su mapa tiene la estación de Atocha marcada en rojo.",11),
      sus("el-estudiante-arte","El Estudiante de Arte","Nico Ferrer Gil",22,
          "Es un chico alto de veintidós años. Lleva un tubo de carteles porque estudia en la academia de arte. Va al Retiro a dibujar cada domingo con sus amigos.",15),
      sus("la-fotografa","La Fotógrafa","Elena Ríos Campos",31,
          "Es una mujer de treinta y un años con una cámara profesional que usa constantemente. Fotografía los parques de Madrid para una revista de viajes.",29),
      sus("el-guia-turistico","El Guía Turístico","Óscar Peña Molina",45,
          "Es un hombre bajo de cuarenta y cinco años con sombrero y mapa. Trabaja con grupos grandes de turistas — ayer guió a treinta personas por el Prado.",7),
      sus("la-jubilada","La Jubilada","Pilar Vega Ortiz",67,
          "Es una señora de sesenta y siete años que camina por el Retiro todas las tardes. Conoce al vigilante y siempre saluda a todos.",44),
    ]),
),
4: dict(
  caseTitle="La Reunión Familiar", criminalName="La Prima Perdida",
  caseDescription="En la gran reunión anual de la familia Solano, cerca del Volcán Arenal, el reloj de oro del abuelo desapareció durante la cena. Todos son familia… pero una 'prima' que nadie recuerda bien llegó sin invitación. Caso frío: pistas difíciles y puntos dobles.",
  bonusClue="La sospechosa dijo ser 'la prima de Puntarenas', pero la familia de Puntarenas no la conoce.",
  briefing=["Agente, pura vida — pero no para la familia Solano.",
            "El reloj de oro del abuelo desapareció durante la reunión familiar cerca del Arenal.",
            "Todos los invitados son familia… menos una 'prima' que nadie recuerda bien.",
            "Es un caso frío: entrevistas solo en español y puntos dobles. Cuidado con ser y estar, agente."],
  dialogue=dlg("Tía Elena Solano", "👩‍🦳",
    "La 'prima' está nerviosa toda la noche y no conoce el nombre del perro de la familia.",
    "¡Bienvenido, mijo! ¿Tú eres el detective? Estamos muy preocupados por el reloj del abuelo.",
    [opt("Buenas noches, doña Elena. Soy detective. ¿Cómo está la familia?", True, "info"),
     opt("¿Dónde está la comida? Tengo hambre.", False, fb="¡La cena puede esperar! Saluda con respeto y pregunta por la familia."),
     opt("Usted es la ladrona, ¿verdad?", False, fb="¡Sin evidencia no acusamos a nadie! Primero saluda y escucha.")],
    "Estamos tristes y preocupados. Pero mira: mi sobrina Gabriela ESTÁ rara esta noche. Normalmente ES tranquila, pero hoy está nerviosa y mira la puerta todo el tiempo.",
    [opt("¿Quién es la invitada nueva? ¿De dónde es?", True, "detail"),
     opt("¿El abuelo está enojado?", False, fb="El abuelo está triste, claro. Pregunta por la invitada que nadie conoce."),
     opt("¿Cuántos años tiene el reloj?", False, fb="La historia del reloj no importa ahora. Pregunta por la 'prima' misteriosa.")],
    "Dice que es 'la prima de Puntarenas', pero llamé a mi hermana de Puntarenas… ¡y no la conoce! Y cuando el perro Firulais llegó, ella preguntó su nombre. ¡Toda la familia conoce a Firulais!",
    "La tía Elena te aprieta el brazo. La 'prima' está cerca de la mesa de postres."),
  reading=dict(
    clue="La 'prima' llegó sin invitación a las 19:30, estuvo sola cerca del cuarto del abuelo, y su carro tiene placas de San José, no de Puntarenas.",
    passage="NOTAS DEL ORGANIZADOR — REUNIÓN FAMILIAR SOLANO\nLugar: finca cerca del Volcán Arenal\n\n18:00 — Llegan las familias de San José y de Limón. Todos están alegres.\n19:30 — Llega una mujer sola. Dice: 'Soy Marcela, la prima de Puntarenas.' No tiene invitación, pero es la reunión familiar — nadie pregunta más.\n20:15 — Durante la cena, 'Marcela' no está en la mesa. El primo Diego la ve en el pasillo, cerca del cuarto del abuelo.\n20:45 — El abuelo busca su reloj de oro para la foto familiar. El reloj no está en su caja.\n21:00 — 'Marcela' dice que está cansada y que su hotel está lejos. Sale rápido.\nNota: Su carro tiene placas de San José — no de Puntarenas.",
    glossary=[{"word":"finca","translation":"farm / country estate"},{"word":"invitación","translation":"invitation"},
              {"word":"pasillo","translation":"hallway"},{"word":"caja","translation":"box"},
              {"word":"placas","translation":"license plates"},{"word":"postres","translation":"desserts"}],
    questions=[
      mc("cr1","¿A qué hora llegó la 'prima de Puntarenas'?",["18:00","19:30","20:15","21:00"],1,
         "Las notas dicen: «19:30 — Llega una mujer sola».","She arrived alone at 19:30, without an invitation."),
      mc("cr2","¿Dónde estaba 'Marcela' durante la cena?",["En la mesa","En la cocina","En el pasillo, cerca del cuarto del abuelo","En el jardín"],2,
         "Diego la ve «en el pasillo, cerca del cuarto del abuelo» — usamos ESTAR para la ubicación.","Estar for location: she WAS in the hallway near grandpa's room."),
      mc("cr3","¿Por qué es sospechoso su carro?",["Es muy viejo","Tiene placas de San José","Es rojo","No tiene placas"],1,
         "Dice ser de Puntarenas, pero su carro «tiene placas de San José».","She claims Puntarenas but her plates say San José."),
      sa("cr4","¿Qué busca el abuelo para la foto? (Escribe en español.)",["su reloj de oro","el reloj de oro","el reloj","su reloj"],
         "El abuelo busca «su reloj de oro para la foto familiar».","He wanted his gold watch for the family photo."),
    ]),
  lineup=dict(
    hint="Busca a la invitada que ESTÁ nerviosa (aunque parece tranquila), llegó sola a las 19:30, no conoce al perro y tiene carro con placas de San José.",
    correct="la-prima-perdida",
    suspects=[
      sus("la-prima-perdida","La Prima Perdida","'Marcela' — nombre real desconocido",33,
          "Es una mujer de treinta y tres años, delgada y elegante. Dice ser de Puntarenas. Está nerviosa toda la noche, no conoce al perro de la familia y su carro es de San José.",26),
      sus("la-sobrina","La Sobrina","Gabriela Solano Mora",24,
          "Es una chica de veinticuatro años, normalmente tranquila pero hoy está nerviosa — ¡porque su novio viene a conocer a la familia! Conoce a Firulais desde niña.",19),
      sus("el-primo","El Primo","Diego Solano Vargas",29,
          "Es un hombre alegre de veintinueve años. Estuvo en la mesa toda la cena contando chistes. Él vio a 'Marcela' en el pasillo.",3),
      sus("la-vecina","La Vecina","Doña Rosario Quesada",58,
          "Es la vecina de la finca, de cincuenta y ocho años. Trajo un pastel de café. Conoce a la familia hace veinte años y conoce muy bien a Firulais.",47),
      sus("el-fotografo-familia","El Fotógrafo","Tomás Brenes Rojas",41,
          "Es el fotógrafo contratado, de cuarenta y un años. Estuvo preparando las luces para la foto familiar en el jardín toda la noche.",10),
    ]),
),
5: dict(
  caseTitle="El Prototipo Robado", criminalName="La Ingeniera Fantasma",
  caseDescription="En la Expo Tech de Buenos Aires, el prototipo de un teléfono revolucionario desapareció del stand de OMEGA — un año después del gran hackeo. Una 'ingeniera invitada' con credencial falsa es la principal sospechosa. Caso frío: números, fechas y puntos dobles.",
  bonusClue="La credencial falsa tiene un error: dice '31 de febrero' como fecha de emisión. ¡Esa fecha no existe!",
  briefing=["Agente, Buenos Aires otra vez. El Edificio OMEGA nos llama.",
            "El prototipo del teléfono OMEGA X desapareció de la Expo Tech — vale dos millones de dólares.",
            "Una 'ingeniera invitada' entró con una credencial falsa. Es profesional y conoce la tecnología.",
            "Caso frío: los números y las fechas son la clave. Puntos dobles. ¡Vamos!"],
  dialogue=dlg("Facundo, el guardia de la Expo", "💂",
    "La sospechosa preguntó el código del depósito y dijo tener treinta años… pero su credencial dice cuarenta.",
    "¡Che, buenas! ¿Vos sos el detective? Acá pasó algo grande, te cuento.",
    [opt("Buenas tardes, Facundo. Soy detective. ¿Qué vio usted en el stand de OMEGA?", True, "info"),
     opt("¿Dónde puedo comprar un teléfono nuevo?", False, fb="¡No estás de compras! Preséntate y pregunta por el robo del prototipo."),
     opt("¿Qué es una Expo Tech?", False, fb="Ya sabes qué es — pregunta por lo que vio el guardia.")],
    "Una mujer con credencial de 'ingeniera invitada' preguntó el código del depósito. Dijo: 'Tengo treinta años de experiencia'… pero su credencial dice que tiene cuarenta años. ¡Los números no funcionan, che!",
    [opt("¿Qué más recuerda de la credencial?", True, "detail"),
     opt("¿Usted tiene hambre?", False, fb="¡Concentración, agente! Pregunta por los detalles de la credencial."),
     opt("¿Cuántos stands hay en la Expo?", False, fb="El número de stands no importa. La credencial falsa es la pista.")],
    "La credencial tenía la fecha de emisión: ¡31 de febrero! Esa fecha no existe. Y el número de empleada era 0000. Nadie revisó porque ella hablaba con mucha seguridad.",
    "Facundo te muestra la foto de la cámara de seguridad. La cara está clara."),
  reading=dict(
    clue="La sospechosa entró a las 14:00 del 15 de marzo, fue al depósito a las 15:30, y el prototipo desapareció entre las 15:30 y las 15:45.",
    passage="REGISTRO DIGITAL — EXPO TECH BUENOS AIRES, STAND OMEGA\nFecha: sábado, 15 de marzo\n\n14:00 — Entra 'Ing. Valeria Núñez', credencial número 0000, fecha de emisión 31 de febrero. El sistema no verifica la fecha.\n14:30 — La visitante hace muchas preguntas sobre el prototipo OMEGA X: cuánto pesa, cuánto cuesta, dónde duerme de noche.\n15:30 — La cámara del depósito registra una entrada con el código de mantenimiento. El prototipo está en su caja.\n15:45 — La cámara registra la salida. La caja del prototipo está vacía.\n16:00 — 'Valeria Núñez' no está en la Expo. Su credencial queda en un basurero.\nNota: OMEGA no tiene ninguna empleada ni invitada con ese nombre.",
    glossary=[{"word":"credencial","translation":"badge / credential"},{"word":"emisión","translation":"issue (date)"},
              {"word":"depósito","translation":"storage room"},{"word":"mantenimiento","translation":"maintenance"},
              {"word":"basurero","translation":"trash can"},{"word":"pesa","translation":"weighs"}],
    questions=[
      mc("cr1","¿Qué fecha de emisión tiene la credencial falsa?",["28 de febrero","30 de enero","31 de febrero","15 de marzo"],2,
         "La credencial dice «31 de febrero» — ¡febrero nunca tiene 31 días!","February 31st doesn't exist — the fake badge's giveaway."),
      mc("cr2","¿Qué número de empleada tenía la credencial?",["0000","1234","4040","9999"],0,
         "El registro dice «credencial número 0000» — un número imposible.","Badge number 0000 — an impossible employee number."),
      mc("cr3","¿Entre qué horas desapareció el prototipo?",["14:00 y 14:30","14:30 y 15:30","15:30 y 15:45","16:00 y 17:00"],2,
         "La cámara registra entrada a las 15:30 con el prototipo en su caja y salida a las 15:45 con la caja vacía.","Between the 15:30 entry and 15:45 exit, the box was emptied."),
      sa("cr4","¿Dónde queda la credencial al final? (Escribe en español.)",["en un basurero","en el basurero","basurero"],
         "El registro dice: «Su credencial queda en un basurero».","She dumped the badge in a trash can."),
    ]),
  lineup=dict(
    hint="Busca a una mujer de unos 40 años que habla con mucha seguridad sobre tecnología, dice tener 30 años de experiencia y usa el código de mantenimiento.",
    correct="la-ingeniera-fantasma",
    suspects=[
      sus("la-ingeniera-fantasma","La Ingeniera Fantasma","'Valeria Núñez' — identidad falsa",40,
          "Es una mujer de cuarenta años, segura y muy inteligente. Sabe todo sobre teléfonos y códigos. Dice tener treinta años de experiencia — los números no funcionan.",34),
      sus("la-disenadora","La Diseñadora","Camila Ferreyra Paz",29,
          "Es una diseñadora de veintinueve años del stand vecino. Tiene credencial real número 2847. Estuvo presentando su aplicación toda la tarde.",24),
      sus("el-tecnico-expo","El Técnico","Martín Ocampo Silva",35,
          "Es el técnico de mantenimiento de treinta y cinco años. Tiene el código del depósito, pero las cámaras lo muestran arreglando luces en el otro pabellón.",5),
      sus("el-periodista","El Periodista","Bruno Aguirre Costa",44,
          "Es un periodista de tecnología de cuarenta y cuatro años. Hace muchas preguntas sobre precios y fechas, pero su credencial de prensa es real y verificada.",17),
      sus("la-estudiante-ing","La Estudiante","Sofía Bianchi Vera",21,
          "Es una estudiante de ingeniería de veintiún años. Visitó el stand tres veces porque quiere trabajar en OMEGA. Su mochila es demasiado pequeña para el prototipo.",39),
    ]),
),
6: dict(
  caseTitle="El Libro de Especias", criminalName="La Crítica",
  caseDescription="El libro secreto de especias de la Escuela de Cocina de Cartagena — cien años de recetas familiares — desapareció la noche de la gran cena de graduación. Una crítica gastronómica misteriosa reservó mesa… con nombre falso. Caso frío con sabor a puntos dobles.",
  bonusClue="La sospechosa pidió ESTE plato, no ESE plato — sabía exactamente qué receta venía del libro secreto.",
  briefing=["Agente, bienvenido a Cartagena. Huele a arepas… y a problemas.",
            "El libro secreto de especias de la Escuela de Cocina desapareció durante la cena de graduación.",
            "Una crítica gastronómica reservó mesa con nombre falso. Conoce las recetas demasiado bien.",
            "Caso frío: este plato, ese plato, aquel ladrón. Puntos dobles. ¡Buen provecho, agente!"],
  dialogue=dlg("Chef Emilia, la directora", "👩‍🍳",
    "La 'crítica' entró a la cocina diciendo que buscaba el baño — dos veces.",
    "¡Bienvenido! ¿Tú eres el detective? Esta cocina está de luto — perdimos cien años de recetas.",
    [opt("Buenas noches, chef Emilia. Soy detective. Cuénteme sobre la cena de anoche.", True, "info"),
     opt("¿Me prepara unas arepas primero?", False, fb="¡Las arepas después! Saluda a la chef y pregunta por la cena."),
     opt("¿Dónde compran las especias?", False, fb="Las especias no son la pista. Pregunta qué pasó anoche.")],
    "Anoche vino una crítica gastronómica que nadie conoce. Probó este plato, ese plato, todos los platos… y entró a la cocina dos veces 'buscando el baño'. ¡El baño está al otro lado!",
    [opt("¿Qué preguntó ella sobre las recetas?", True, "detail"),
     opt("¿Quién lavó los platos?", False, fb="Los platos limpios no importan. Pregunta qué dijo la 'crítica'."),
     opt("¿A qué hora cierran?", False, fb="El horario no es la pista — pregunta por la mujer misteriosa.")],
    "Preguntó por el ají secreto de la abuela Rosa — ¡una receta que SOLO está en el libro! Nadie fuera de la escuela conoce ese nombre. Y pidió la mesa junto a la puerta de la cocina.",
    "La chef Emilia te da la reserva de la mesa: 'Sra. Paladar'. Nombre falso, pista real."),
  reading=dict(
    clue="La 'crítica' reservó con nombre falso, se sentó junto a la cocina, y salió durante el brindis con un bolso más gordo.",
    passage="LIBRO DE RESERVAS — ESCUELA DE COCINA DE CARTAGENA\nNoche de graduación, viernes\n\n19:00 — Reserva a nombre de 'Sra. Paladar', mesa 12, junto a la puerta de la cocina. Pidió esa mesa específicamente.\n19:45 — La señora prueba el menú de degustación. Pregunta por el ají secreto de la abuela Rosa. El mesero no conoce ese nombre.\n20:30 — La señora va 'al baño' por la puerta de la cocina. El baño está al lado opuesto del restaurante.\n21:00 — Durante el brindis de graduación, todos miran al escenario. La señora no está en la mesa 12.\n21:10 — La señora regresa, paga en efectivo y sale. Su bolso se ve más gordo que antes.\n22:00 — La chef descubre que el libro de especias no está en su estante de la cocina.",
    glossary=[{"word":"reserva","translation":"reservation"},{"word":"degustación","translation":"tasting (menu)"},
              {"word":"ají","translation":"chili pepper (sauce)"},{"word":"brindis","translation":"toast"},
              {"word":"efectivo","translation":"cash"},{"word":"estante","translation":"shelf"}],
    questions=[
      mc("cr1","¿Qué mesa pidió la 'Sra. Paladar'?",["La mesa del jardín","La mesa 12, junto a la cocina","La mesa del centro","La barra"],1,
         "La reserva dice: «mesa 12, junto a la puerta de la cocina. Pidió esa mesa específicamente».","She specifically requested table 12 by the kitchen door."),
      mc("cr2","¿Por qué es sospechosa su pregunta sobre el ají?",["Porque no le gusta el ají","Porque esa receta solo está en el libro secreto","Porque el ají es caro","Porque el mesero es nuevo"],1,
         "El ají secreto de la abuela Rosa SOLO está en el libro — nadie de afuera conoce ese nombre.","Only the secret book contains that recipe name."),
      mc("cr3","¿Cuándo desapareció la señora de su mesa?",["Durante la cena","Durante el brindis","Al pagar","Al llegar"],1,
         "«Durante el brindis de graduación, todos miran al escenario. La señora no está en la mesa 12.»","She vanished exactly when everyone watched the toast."),
      sa("cr4","¿Cómo pagó la señora? (Escribe en español.)",["en efectivo","efectivo","con efectivo"],
         "El registro dice: «paga en efectivo» — sin tarjeta, sin nombre real.","Cash — no card, no real name."),
    ]),
  lineup=dict(
    hint="Busca a una mujer que conoce las recetas secretas, pidió la mesa junto a la cocina, y prefiere ESTE plato picante — no ese ni aquel.",
    correct="la-critica",
    suspects=[
      sus("la-critica","La Crítica","'Sra. Paladar' — nombre falso",48,
          "Es una mujer elegante de cuarenta y ocho años. Conoce cada especia y cada receta. Prefiere este ají picante, no ese dulce. Su bolso siempre es grande.",37),
      sus("el-mesero","El Mesero","Andrés Cabrera Luna",26,
          "Es un mesero de veintiséis años, rápido y amable. Sirvió las mesas 10, 11 y 12 toda la noche. No conoce el ají de la abuela Rosa.",6),
      sus("la-graduada","La Graduada","Luisa Mendoza Prieto",23,
          "Es una estudiante de veintitrés años que se graduó anoche. Estuvo en el escenario durante todo el brindis, delante de doscientas personas.",31),
      sus("el-proveedor","El Proveedor","Ramón Castillo Duarte",52,
          "Es el proveedor de especias de la escuela, de cincuenta y dos años. Conoce muchas recetas, pero anoche entregaba especias en Barranquilla.",12),
      sus("la-abuela-rosa","La Abuela Rosa","Rosa Herrera de Díaz",79,
          "Es la abuela de setenta y nueve años, autora de las recetas. El libro es SU tesoro — estuvo en la mesa de honor toda la noche, feliz y orgullosa.",49),
    ]),
),
7: dict(
  caseTitle="La Gaviota de Oro", criminalName="La Cantante Enmascarada",
  caseDescription="El trofeo Gaviota de Oro del Festival de Viña del Mar desapareció la noche antes de la gran final. Una cantante enmascarada del concurso de talentos es la principal sospechosa — pero hay cinco artistas y todos llevan máscara en el ensayo. Caso frío, primer premio: puntos dobles.",
  bonusClue="La sospechosa canta en segundo lugar en el programa — y su camerino es el tercero, el más cercano a la sala de trofeos.",
  briefing=["Agente, ¡el Festival de Viña está en crisis!",
            "La Gaviota de Oro desapareció la noche antes de la final. Sin trofeo, no hay festival.",
            "Sospechamos de una cantante enmascarada del concurso. Pero en el ensayo… todos llevan máscara.",
            "Caso frío: primero, segundo, tercero — los ordinales son la clave. ¡Puntos dobles, agente!"],
  dialogue=dlg("Nico, el técnico de sonido", "🎧",
    "La sospechosa ensayó fuera de su turno y preguntó cuándo apagan las luces del pasillo de trofeos.",
    "¡Hola! ¿El detective? Qué bueno, porque aquí está pasando algo muy raro con los ensayos.",
    [opt("Buenas tardes, Nico. Soy detective. ¿Qué notó usted en el ensayo de anoche?", True, "info"),
     opt("¿Me consigues entradas para la final?", False, fb="¡Las entradas después! Pregunta por el ensayo de anoche."),
     opt("¿Qué tiempo hace en Viña?", False, fb="El tiempo no importa dentro del teatro. Pregunta por los ensayos.")],
    "Anoche una cantante ensayó FUERA de su turno. Su turno es el segundo, pero ensayó en el quinto, la última. Y me preguntó a qué hora apagamos las luces del pasillo de trofeos. ¡Qué pregunta más rara!",
    [opt("¿Recuerda algo de su voz o su ropa?", True, "detail"),
     opt("¿Cuál es tu canción favorita?", False, fb="La música después — pregunta por la descripción de la cantante."),
     opt("¿Las luces son nuevas?", False, fb="Las luces no son la pista. La cantante que preguntó por ellas, sí.")],
    "Voz grave, máscara plateada, y llevaba impermeable — ¡pero anoche no llovió! Estaba nublado, sí, pero no cayó ni una gota. ¿Para qué un impermeable seco?",
    "Nico te pasa el programa del festival con los turnos marcados. Segunda en cantar, tercera en camerino."),
  reading=dict(
    clue="El trofeo desapareció entre las 22:00 y las 22:20, cuando las luces del pasillo estaban apagadas y la cantante del segundo turno no estaba en su camerino.",
    passage="INFORME NOCTURNO — TEATRO DEL FESTIVAL, VIÑA DEL MAR\nNoche del ensayo general (nublado, sin lluvia)\n\n21:00 — Termina el ensayo general. Los cinco artistas van a sus camerinos: primero, segundo, tercero, cuarto y quinto.\n21:45 — La artista del segundo turno pide ensayar otra vez, en el quinto lugar, la última.\n22:00 — Las luces del pasillo de trofeos se apagan por mantenimiento programado, veinte minutos exactos.\n22:05 — El guardia pasa por los camerinos. El camerino tercero está vacío — es el camerino de la artista del segundo turno.\n22:20 — Las luces vuelven. La vitrina de la Gaviota de Oro está abierta y vacía.\n22:30 — La artista del segundo turno regresa a su camerino con un bolso de ropa 'para la lavandería'. La lavandería cierra a las 21:00.",
    glossary=[{"word":"ensayo","translation":"rehearsal"},{"word":"camerino","translation":"dressing room"},
              {"word":"turno","translation":"turn / slot"},{"word":"impermeable","translation":"raincoat"},
              {"word":"nublado","translation":"cloudy"},{"word":"lavandería","translation":"laundry"}],
    questions=[
      mc("cr1","¿Cuánto tiempo estuvieron apagadas las luces del pasillo?",["Diez minutos","Veinte minutos","Treinta minutos","Toda la noche"],1,
         "El informe dice: «veinte minutos exactos» — de 22:00 a 22:20.","Exactly twenty minutes of darkness — the theft window."),
      mc("cr2","¿Qué camerino estaba vacío a las 22:05?",["El primero","El segundo","El tercero","El quinto"],2,
         "«El camerino tercero está vacío» — el de la artista del segundo turno. ¡Ordinales!","The THIRD dressing room (of the SECOND performer) was empty."),
      mc("cr3","¿Qué tiempo hacía esa noche?",["Llovía mucho","Estaba nublado, sin lluvia","Hacía sol","Nevaba"],1,
         "El informe dice: «nublado, sin lluvia» — por eso el impermeable seco es sospechoso.","Cloudy but dry — so why the raincoat?"),
      sa("cr4","¿A qué hora cierra la lavandería? (Escribe la hora en números.)",["21:00","9:00","a las 21:00","las 21:00"],
         "La lavandería cierra a las 21:00 — su excusa del bolso es falsa.","The laundry closed at 21:00 — her laundry-bag excuse is fake."),
    ]),
  lineup=dict(
    hint="Busca a la artista del SEGUNDO turno con el camerino TERCERO: voz grave, máscara plateada y un impermeable en una noche sin lluvia.",
    correct="la-cantante-enmascarada",
    suspects=[
      sus("la-cantante-enmascarada","La Cantante Enmascarada","Renata Fuentes Alba",36,
          "Es una cantante de treinta y seis años con voz grave y máscara plateada. Canta en el segundo turno y su camerino es el tercero. Anoche llevaba impermeable… sin lluvia.",42),
      sus("el-bajista","El Bajista","Cristóbal Rojas Pinto",33,
          "Es un músico de treinta y tres años con voz grave. Toca en el quinto turno y su camerino es el primero, al otro lado del teatro. Estuvo afinando su bajo con Nico.",9),
      sus("la-bailarina","La Bailarina","Josefa Aravena Cruz",27,
          "Es una bailarina de veintisiete años con máscara dorada, no plateada. Baila en el cuarto turno y ensayó su coreografía en el escenario hasta las 22:30 — todos la vieron.",35),
      sus("el-presentador","El Presentador","Rodrigo Salas Bravo",50,
          "Es el presentador del festival, de cincuenta años. No lleva máscara y estuvo grabando promociones frente a las cámaras de 21:30 a 22:30.",14),
      sus("la-vestuarista","La Vestuarista","Amanda Leiva Soto",45,
          "Es la vestuarista de cuarenta y cinco años. Lleva ropa de todos los artistas a la lavandería… pero siempre antes de las 21:00, cuando cierra.",50),
    ]),
),
8: dict(
  caseTitle="El Telar de la Abuela", criminalName="El Anticuario",
  caseDescription="Un telar ceremonial de 300 años desapareció de la cooperativa de tejedoras de Cusco, una semana después del caso del mercado. Un 'anticuario' extranjero visitó la cooperativa tres veces y regateó un precio imposible. Caso frío en pretérito: puntos dobles.",
  bonusClue="El sospechoso pagó todo en el mercado con billetes nuevos de cien soles — y ayer alguien cambió mil dólares en la casa de cambio de la esquina.",
  briefing=["Agente, Cusco te necesita otra vez.",
            "Un telar ceremonial de trescientos años desapareció de la cooperativa de tejedoras.",
            "Un 'anticuario' visitó tres veces, regateó, y la abuela Julia dijo que no. Anoche, el telar desapareció.",
            "Caso frío en pretérito: ¿qué pasó, quién llegó, quién salió? Puntos dobles. ¡Vamos!"],
  dialogue=dlg("Abuela Julia, la tejedora mayor", "🧶",
    "El 'anticuario' ofreció mil soles, la abuela dijo que no, y él respondió: 'Entonces lo conseguiré de otra manera.'",
    "Bienvenido, joven. ¿Usted es el detective? Ese telar perteneció a mi bisabuela. Ayúdenos, por favor.",
    [opt("Buenos días, abuela Julia. Soy detective. ¿Qué pasó con el anticuario?", True, "info"),
     opt("¿Cuánto cuesta esta manta?", False, fb="No viniste de compras. Saluda con respeto y pregunta por el anticuario."),
     opt("¿Dónde está el mercado de San Pedro?", False, fb="Ya conoces el mercado. Pregunta qué pasó con el telar.")],
    "El hombre vino tres veces. La primera vez miró todo. La segunda vez preguntó precios. La tercera vez ofreció mil soles por el telar ceremonial. Le dije que no — no está a la venta.",
    [opt("¿Qué dijo él cuando usted dijo que no?", True, "detail"),
     opt("¿Usted vendió otras mantas?", False, fb="Las otras ventas no importan. Pregunta qué RESPONDIÓ el anticuario."),
     opt("¿El telar es bonito?", False, fb="Es hermoso, claro. Pregunta por la reacción del hombre.")],
    "Me miró muy serio y dijo: 'Entonces lo conseguiré de otra manera.' Salió sin despedirse. Esa noche alguien entró por la ventana del taller y el telar desapareció.",
    "La abuela Julia te muestra la ventana. Hay una huella de bota europea, talla 44."),
  reading=dict(
    clue="El ladrón entró por la ventana entre la medianoche y las 2:00, conocía el taller, y dejó una huella de bota talla 44.",
    passage="DECLARACIÓN POLICIAL — COOPERATIVA DE TEJEDORAS, CUSCO\nDeclarante: vecino Mateo Quispe\n\nAnoche escuché ruidos en el taller de la cooperativa. Miré por mi ventana a la medianoche y vi una luz pequeña adentro. Pensé: 'las tejedoras trabajaron tarde'. Pero las tejedoras salieron a las ocho — yo las vi salir.\nA la una de la mañana, un hombre alto salió por la ventana del taller. Cargó un bulto largo envuelto en plástico. Caminó rápido hacia la Plaza de Armas. Llevó el bulto con mucho cuidado, como algo muy delicado.\nEsta mañana encontré una huella de bota junto a la ventana. Una bota europea, grande, talla 44. Los policías fotografiaron la huella.\nEn la casa de cambio me contaron: ayer un extranjero cambió mil dólares en billetes nuevos de cien soles.",
    glossary=[{"word":"declaración","translation":"statement"},{"word":"bulto","translation":"bundle / package"},
              {"word":"envuelto","translation":"wrapped"},{"word":"huella","translation":"footprint"},
              {"word":"talla","translation":"size"},{"word":"casa de cambio","translation":"currency exchange"}],
    questions=[
      mc("cr1","¿A qué hora salieron las tejedoras del taller?",["A la medianoche","A las ocho","A la una","A las diez"],1,
         "Mateo dice: «las tejedoras salieron a las ocho — yo las vi salir». Pretérito: salieron.","Preterite 'salieron' — they left at eight."),
      mc("cr2","¿Qué vio Mateo a la una de la mañana?",["Una fiesta","Un hombre alto con un bulto largo","Un carro rojo","A las tejedoras"],1,
         "«Un hombre alto salió por la ventana… Cargó un bulto largo.» Pretérito: salió, cargó.","He saw a tall man climb out carrying a long bundle."),
      mc("cr3","¿Qué encontró Mateo esta mañana?",["Una carta","Dinero","Una huella de bota talla 44","El telar"],2,
         "«Encontré una huella de bota… talla 44.» Pretérito: encontré.","Preterite 'encontré' — he found the size-44 boot print."),
      sa("cr4","¿Cuánto dinero cambió el extranjero? (Escribe en español o números.)",["mil dólares","mil","1000","1000 dólares"],
         "«Un extranjero cambió mil dólares en billetes nuevos.» Pretérito: cambió.","He exchanged a thousand dollars — 'cambió' (preterite)."),
    ]),
  lineup=dict(
    hint="Busca a un hombre alto y extranjero con botas europeas talla 44, que ofreció mil soles, pagó con billetes nuevos y dijo: 'Lo conseguiré de otra manera.'",
    correct="el-anticuario",
    suspects=[
      sus("el-anticuario","El Anticuario","Klaus Weber Montt",55,
          "Es un hombre alto y extranjero de cincuenta y cinco años. Colecciona textiles antiguos. Visitó la cooperativa tres veces, ofreció mil soles y pagó todo con billetes nuevos. Usa botas europeas talla 44.",18),
      sus("el-mochilero","El Mochilero","Jonas Berg Olsen",24,
          "Es un turista alto de veinticuatro años con botas europeas talla 45. Llegó a Cusco ayer por la tarde y durmió en el hostal — el recepcionista lo confirmó.",21),
      sus("el-comerciante","El Comerciante","Faustino Huamán Ríos",47,
          "Es un comerciante del mercado de San Pedro, de cuarenta y siete años. Vende mantas modernas y conoce a la abuela Julia hace años. Calza talla 40.",16),
      sus("la-coleccionista","La Coleccionista","Ingrid Solberg Paz",60,
          "Es una coleccionista extranjera de sesenta años. Compró tres mantas la semana pasada — pagó bien y con recibo. Anoche cenó con el alcalde, frente a veinte personas.",53),
      sus("el-guia-cusco","El Guía","Percy Condori Mamani",31,
          "Es un guía turístico de treinta y un años. Lleva grupos a la cooperativa cada semana. Anoche guió el tour nocturno de la ciudad hasta las dos.",2),
    ]),
),
9: dict(
  caseTitle="El Ámbar de la Clínica", criminalName="El Farmacéutico",
  caseDescription="El collar de ámbar dominicano — pieza central de la subasta benéfica de la Clínica Central — desapareció el día de la feria de salud. Un 'farmacéutico voluntario' al que nadie contrató atendió el puesto junto a la vitrina… y a él no le dolía nada. Caso frío: puntos dobles.",
  bonusClue="El 'farmacéutico' dijo que le dolía la cabeza para entrar al área de descanso — pero el área de descanso está al lado de la vitrina del ámbar.",
  briefing=["Agente, Santo Domingo otra vez — y esta vez la víctima es una clínica.",
            "El collar de ámbar de la subasta benéfica desapareció durante la feria de salud.",
            "Un 'farmacéutico voluntario' que nadie contrató trabajó junto a la vitrina toda la mañana.",
            "Caso frío: ¿a quién le duele qué? El verbo doler es tu mejor testigo. ¡Puntos dobles!"],
  dialogue=dlg("Enfermera Yolanda", "👩‍⚕️",
    "El 'farmacéutico' no sabía tomar la presión — y dijo tres veces que le dolía la cabeza para ir al área de descanso.",
    "¡Hola de nuevo, detective! Sí, otra vez yo. Esta clínica me va a matar de estrés. ¿Empezamos?",
    [opt("Buenos días, enfermera Yolanda. Un gusto verla. ¿Qué notó en la feria de salud?", True, "info"),
     opt("Me duele el estómago, ¿me atiende?", False, fb="¡Ja! A ti no te duele nada. Saluda y pregunta por la feria de salud."),
     opt("¿Dónde está la farmacia?", False, fb="La farmacia no es la pista — el 'farmacéutico' falso, sí.")],
    "El 'farmacéutico voluntario' fue rarísimo. Le pedí ayuda para tomar la presión a un paciente… ¡y no sabía usar el aparato! ¿Un farmacéutico que no sabe tomar la presión?",
    [opt("¿Qué más hizo él durante la mañana?", True, "detail"),
     opt("¿A usted le duele algo?", False, fb="A Yolanda le duele el estrés — pero pregunta por el farmacéutico falso."),
     opt("¿Cuántos pacientes vinieron?", False, fb="El número de pacientes no importa. Los movimientos del 'farmacéutico', sí.")],
    "Tres veces dijo: 'Me duele la cabeza, necesito descansar.' Y fue al área de descanso — que está JUSTO al lado de la vitrina del collar. A la tercera vez, no regresó. Y el collar tampoco.",
    "Yolanda cruza los brazos: 'Una persona con dolor de cabeza no camina tan rápido, mijo.'"),
  reading=dict(
    clue="El 'farmacéutico' llegó sin cita a las 8:30, fue tres veces al área de descanso, y desapareció a las 11:40 — cinco minutos antes del descubrimiento.",
    passage="CUADERNO DE LA FERIA DE SALUD — CLÍNICA CENTRAL\nSábado, feria benéfica\n\n08:30 — Llega un 'farmacéutico voluntario' con bata blanca. No está en la lista de voluntarios, pero dice: 'Me mandó la fundación.' Nadie verifica.\n09:15 — El farmacéutico atiende el puesto de medicinas, junto a la vitrina del collar de ámbar.\n10:00 — Primera visita al área de descanso: 'Me duele la cabeza.'\n10:45 — Segunda visita: 'Todavía me duele la cabeza.' El doctor le ofrece una pastilla. El farmacéutico dice que no.\n11:30 — Tercera visita al área de descanso. Esta vez lleva su mochila.\n11:40 — El farmacéutico no regresa a su puesto.\n11:45 — La directora descubre la vitrina abierta. El collar de ámbar no está.\nNota: Un farmacéutico real acepta una pastilla cuando le duele la cabeza.",
    glossary=[{"word":"bata","translation":"lab coat"},{"word":"fundación","translation":"foundation"},
              {"word":"puesto","translation":"booth / station"},{"word":"pastilla","translation":"pill"},
              {"word":"subasta","translation":"auction"},{"word":"vitrina","translation":"display case"}],
    questions=[
      mc("cr1","¿Cuántas veces fue el 'farmacéutico' al área de descanso?",["Una vez","Dos veces","Tres veces","Cinco veces"],2,
         "El cuaderno registra tres visitas: 10:00, 10:45 y 11:30 — siempre 'me duele la cabeza'.","Three visits, always with the same headache excuse."),
      mc("cr2","¿Por qué es sospechoso que rechazó la pastilla?",["Porque las pastillas son caras","Porque si te duele la cabeza de verdad, aceptas ayuda","Porque era alérgico","Porque no tenía agua"],1,
         "Si de verdad te duele la cabeza, aceptas la pastilla. Él dijo que no — su dolor era mentira.","A real headache accepts a pill — his pain was fake."),
      mc("cr3","¿Qué llevó a la tercera visita?",["Una pastilla","Su mochila","Un vaso de agua","El collar"],1,
         "«Tercera visita… Esta vez lleva su mochila.» — para esconder el collar.","He brought his backpack the third time — to carry the necklace."),
      sa("cr4","¿Qué le dolía al farmacéutico (según él)? (Escribe en español.)",["la cabeza","le dolía la cabeza","me duele la cabeza"],
         "Dijo tres veces: «Me duele la cabeza» — doler + la cabeza.","'Me duele la cabeza' — the verb doler with body parts."),
    ]),
  lineup=dict(
    hint="Busca al hombre de bata blanca que no sabe tomar la presión, dijo tres veces que le dolía la cabeza, rechazó la pastilla y llevó su mochila al descanso.",
    correct="el-farmaceutico",
    suspects=[
      sus("el-farmaceutico","El Farmacéutico","'Dr. Peralta' — identidad falsa",39,
          "Es un hombre de treinta y nueve años con bata blanca nueva. No sabe usar el aparato de presión. Le 'dolía' la cabeza tres veces, pero rechazó la pastilla y caminaba rapidísimo.",23),
      sus("el-doctor","El Doctor","Dr. Samuel Batista Cruz",51,
          "Es el doctor de la clínica, de cincuenta y un años. Atendió cuarenta pacientes en la feria y ofreció la pastilla al 'farmacéutico'. Todos lo conocen hace años.",4),
      sus("la-voluntaria","La Voluntaria","Karina Rosario Peña",20,
          "Es una estudiante de enfermería de veinte años, voluntaria oficial (está en la lista). Le dolían los pies de estar parada, pero no salió del puesto de vacunas.",27),
      sus("el-paciente","El Paciente","Don Aurelio Guzmán",73,
          "Es un paciente de setenta y tres años. Le duele la espalda y las rodillas — de verdad. Esperó su turno sentado toda la mañana, al lado de la enfermera.",46),
      sus("la-organizadora","La Organizadora","Miriam Tavares Luna",44,
          "Es la organizadora de la subasta, de cuarenta y cuatro años. Puso el collar en la vitrina a las 8:00 y estuvo recibiendo donaciones en la entrada, lejos de la vitrina.",32),
    ]),
),
10: dict(
  caseTitle="El Plano del Futuro", criminalName="La Inversora",
  caseDescription="El plano del invento ganador de la Expo del Futuro — un panel solar plegable diseñado por estudiantes de Quito — desapareció la noche de la premiación. Una 'inversora' prometió millones… y pidió ver los planos a solas. Caso frío: el futuro del equipo depende de ti. Puntos dobles.",
  bonusClue="La 'inversora' dijo: 'Mañana firmaremos el contrato.' Pero su vuelo salió anoche — nunca va a firmar nada.",
  briefing=["Agente, Quito — la Expo del Futuro tiene un problema del presente.",
            "El plano del panel solar ganador desapareció la noche de la premiación.",
            "Una 'inversora' prometió millones al equipo estudiantil. Pidió ver los planos a solas… y desaparecieron.",
            "Caso frío: ¿qué va a hacer, adónde irá? El futuro es la clave. ¡Puntos dobles, agente!"],
  dialogue=dlg("Paola, capitana del equipo estudiantil", "👷‍♀️",
    "La 'inversora' fotografió los planos 'para sus socios' y preguntó dónde guardarán el original.",
    "¿Tú eres el detective? Por favor, ayúdanos. Ese plano es nuestro futuro — vamos a cambiar el mundo con ese panel.",
    [opt("Buenas noches, Paola. Soy detective. Cuéntame de la inversora.", True, "info"),
     opt("¿El panel solar funciona de noche?", False, fb="Buena pregunta científica, mal momento. Pregunta por la inversora."),
     opt("¿Van a ganar el premio otra vez?", False, fb="El premio no importa sin el plano. Pregunta por la mujer que lo vio.")],
    "Se llama 'Sra. Ventura'. Dijo: 'Voy a invertir dos millones. Mañana firmaremos el contrato.' Pidió ver los planos a solas, 'sin presión'. Después de su visita, el tubo con los planos estaba vacío.",
    [opt("¿Qué preguntó ella exactamente sobre los planos?", True, "detail"),
     opt("¿Dos millones de dólares o de pesos?", False, fb="La moneda no importa — la promesa era falsa. Pregunta qué dijo de los planos."),
     opt("¿Dónde está el baño?", False, fb="¡Agente, concentración! Pregunta por las palabras exactas de la inversora.")],
    "Preguntó: '¿Dónde guardarán el original esta noche? ¿Quién lo cuidará?' Y fotografió todo 'para sus socios'. Esta mañana llamé a su oficina — el número no existe. Y su vuelo salió ANOCHE.",
    "Paola te muestra la tarjeta de la 'inversora'. El logo es de una empresa que cerró hace años."),
  reading=dict(
    clue="La 'inversora' visitó el stand a las 20:00, preguntó dónde guardarán el plano, y su vuelo a Panamá salió a las 23:55 — antes de la firma 'de mañana'.",
    passage="CORREO AL COMITÉ — EXPO DEL FUTURO, QUITO\nDe: seguridad de la Expo\nAsunto: cronología de la noche de premiación\n\n19:30 — Termina la premiación. El equipo de Paola gana con el panel solar plegable.\n20:00 — La 'inversora Sra. Ventura' visita el stand. Promete: 'Invertiré dos millones. Mañana firmaremos el contrato en mi oficina.'\n20:20 — La inversora pide ver los planos a solas. El equipo celebra afuera — confía en ella.\n20:35 — La inversora sale con su maletín. Dice: 'Los veré mañana a las diez. Traeré a mis abogados.'\n21:00 — El equipo descubre el tubo de planos vacío.\n23:55 — Según el aeropuerto, la Sra. Ventura tomó el vuelo a Panamá. No habrá reunión mañana.\nNota: la oficina de su tarjeta no existe. La empresa cerró hace seis años.",
    glossary=[{"word":"premiación","translation":"award ceremony"},{"word":"plano","translation":"blueprint"},
              {"word":"plegable","translation":"foldable"},{"word":"maletín","translation":"briefcase"},
              {"word":"socios","translation":"business partners"},{"word":"abogados","translation":"lawyers"}],
    questions=[
      mc("cr1","¿Qué prometió la 'inversora'?",["Un carro nuevo","Invertir dos millones","Un viaje a Panamá","Un laboratorio"],1,
         "Dijo: «Invertiré dos millones» — futuro simple del verbo invertir.","'Invertiré' — simple future: I will invest."),
      mc("cr2","¿Qué pidió a las 20:20?",["Un café","Ver los planos a solas","Fotos con el equipo","El premio"],1,
         "«Pide ver los planos a solas» — el momento clave del robo.","She asked to see the blueprints ALONE — the key moment."),
      mc("cr3","¿Qué pasó a las 23:55?",["Firmó el contrato","Tomó el vuelo a Panamá","Llamó a Paola","Regresó a la Expo"],1,
         "«Tomó el vuelo a Panamá» — nunca iba a firmar mañana.","She flew to Panama — the 'tomorrow' meeting was a lie."),
      sa("cr4","¿A qué hora dijo que los verá mañana? (Escribe la hora.)",["a las diez","las diez","10","10:00"],
         "Dijo: «Los veré mañana a las diez» — futuro: veré. Pero su vuelo ya salió.","'Los veré mañana a las diez' — future tense veré… but she was already gone."),
    ]),
  lineup=dict(
    hint="Busca a la mujer que prometió millones en futuro ('invertiré', 'firmaremos', 'traeré')… y tomó un vuelo la misma noche.",
    correct="la-inversora",
    suspects=[
      sus("la-inversora","La Inversora","'Sra. Ventura' — identidad falsa",46,
          "Es una mujer elegante de cuarenta y seis años con maletín de cuero. Promete millones en futuro: 'invertiré, firmaremos, traeré abogados'. Su tarjeta es de una empresa que no existe.",38),
      sus("el-juez","El Juez","Ing. Aurelio Paz Montúfar",58,
          "Es el juez principal de la Expo, de cincuenta y ocho años. Evaluó veinte proyectos y entregó el premio en el escenario, frente a todos, hasta las 21:30.",20),
      sus("la-rival","La Rival","Daniela Chávez Toro",19,
          "Es la capitana del equipo rival, de diecinueve años. Su equipo quedó segundo. Estaba triste, pero celebró con su equipo en la cafetería toda la noche.",40),
      sus("el-periodista-expo","El Periodista","Galo Sandoval Ruiz",36,
          "Es un periodista de ciencia de treinta y seis años. Fotografió TODOS los stands para su artículo — con permiso y credencial real de prensa.",1),
      sus("el-profesor","El Profesor","Dr. Wilson Cárdenas Vela",49,
          "Es el profesor mentor del equipo, de cuarenta y nueve años. Guardó una copia digital del plano en su computadora — por eso el equipo todavía tiene esperanza.",45),
    ]),
),
}

def build(n, spec):
    orig = load(n)
    cut = next(s for s in orig["stages"] if s["type"] == "cutscene")
    cold_cut = dict(cut)
    cold_cut["videoUrl"] = f"/videos/unit-{n:02d}-cold-intro.mp4"  # text-briefing fallback if absent
    cold_cut["briefingLines"] = spec["briefing"]

    vocab_pairs = [{"spanish": v["spanish"], "english": v["english"]} for v in orig["vocab"][:8]]

    r = spec["reading"]
    reading = {"type": "readingComp", "clueReward": r["clue"], "passage": r["passage"],
               "glossary": r["glossary"], "questions": r["questions"]}

    l = spec["lineup"]
    lineup = {"type": "lineup", "correctSuspectId": l["correct"], "hint": l["hint"], "suspects": l["suspects"]}

    out = {
        "unitNumber": n,
        "country": orig["country"],
        "city": orig.get("city", ""),
        "caseTitle": spec["caseTitle"],
        "caseDescription": spec["caseDescription"],
        "criminalName": spec["criminalName"],
        "bonusClue": spec["bonusClue"],
        "isColdCase": True,
        "vocab": orig["vocab"],
        "stages": [cold_cut, {"type": "vocabMatch", "pairs": vocab_pairs}, spec["dialogue"], reading, lineup],
    }
    path = os.path.join(BASE, f"unit-{n:02d}-cold.json")
    with io.open(path, "w", encoding="utf-8", newline="\n") as f:
        json.dump(out, f, ensure_ascii=False, indent=2)
        f.write("\n")
    print(f"wrote unit-{n:02d}-cold.json ({len(json.dumps(out))} chars)")

for n, spec in COLD.items():
    build(n, spec)
print("done")
